version: '3.1'

services:

  php:
    build: docker/php
    container_name: app
    ports:
      - "6111:80"
      - "6112:443"
    volumes:
      - ./app:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    links:
      - database
      - mailer
      - redis
      - rabbitmq
      - blackfire

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: app
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  redis:
    image: "redis:alpine"
    ports: [6379]

  rabbitmq:
    image: rabbitmq:3.7-management

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  blackfire:
    image: blackfire/blackfire:2
    # uncomment to store Blackfire credentials in a local .env.local file
    #env_file: .env.local
    environment:
      BLACKFIRE_LOG_LEVEL: 4
    ports: [ 8307 ]

volumes:
  db-data: